export const states = [
  {
    location: `Lagos Ikeja`,
    state: "Lagos",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "state48t98ruruf7y7dpd",
    desktop: true,
  },
  {
    location: `Adamawa Yola`,
    state: "Adamawa",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statefivj38787d66w43dhvs",
    desktop: true,
  },
  {
    location: `Rivers Portharcourt`,
    state: "Rivers",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "state48r47r6t6f6d66nncbhds",
    desktop: false,
  },
  {
    location: `Oyo Ibadan`,
    state: "Oyo",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statejdhyeg87487e8d8ds78s8",
    desktop: true,
  },
  {
    location: `FCT Abuja`,
    state: "Abuja",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statey327ry87eybcyeywt5",
    desktop: false,
  },
  {
    location: `Imo Owerri`,
    state: "Imo",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "stateydyhdycgoygofyqgf7ow",
    desktop: true,
  },
  {
    location: `Kaduna`,
    state: "Kaduna",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "stateybcuhpuf2388ye78e7f6dt6",
    desktop: false,
  },
  {
    location: `Ondo Akure`,
    state: "Ondo",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statencnu88888c6sw6s6w",
    desktop: true,
  },
  {
    location: `Enugu`,
    state: "Enugu",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statexa8c88ed89f8d8busuisisis",
    desktop: false,
  },
  {
    location: `Kano`,
    state: "Kano",
    link: " https//www.osdhfsdhsdfdf/sfdjfhsdoif/dfj",
    number: "+234 809 987 4567",
    id: "statebdcydgyd87cd86d76d7s",
    desktop: true,
  },
];
